# .github/workflows/update-activity.yml:

name: Update GitHub Activity

on:
  schedule:
    - cron: "*/30 * * * *" # Runs every 30 minutes
  workflow_dispatch: # Allows manual triggering

jobs:
  update-activity:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Update activity log
        uses: ranxion/activity-log@test
        with:
          GITHUB_USERNAME: "ranxion"
          GITHUB_TOKEN: ${{ secrets.TEST123 }} # Ensure this matches the secret name in repository settings
